### ISSUE TITLE
Error when saving project

### ISSUE THREAD

**Issue by multilectical** [ExperimentalFarmNetwork/efn-drupal#126]
this comes up on save

Error: Call to a member function id() on null in /home/onion/www/efn/modules/custom/efn/efn.module on line 244 #0 [internal function]: efn_entity_insert(Object(Drupal\\group\\Entity\\GroupContent))
#1 /home/onion/www/efn/core/lib/Drupal/Core/Extension/ModuleHandler.php(403): call_user_func_array('efn_entity_inse...', Array)
#2 /home/onion/www/efn/core/lib/Drupal/Core/Entity/EntityStorageBase.php(206): Drupal\\Core\\Extension\\ModuleHandler->invokeAll('entity_insert', Array)
#3 /home/onion/www/efn/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php(756): Drupal\\Core\\Entity\\EntityStorageBase->invokeHook('insert', Object(Drupal\\group\\Entity\\GroupContent))
#4 /home/onion/www/efn/core/lib/Drupal/Core/Entity/EntityStorageBase.php(507): Drupal\\Core\\Entity\\ContentEntityStorageBase->invokeHook('insert', Object(Drupal\\group\\Entity\\GroupContent))
#5 /home/onion/www/efn/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php(641): Drupal\\Core\\Entity\\EntityStorageBase->doPostSave(Object(Drupal\\group\\Entity\\GroupContent), false)
#6 /home/onion/www/efn/core/lib/Drupal/Core/Entity/EntityStorageBase.php(432): Drupal\\Core\\Entity\\ContentEntityStorageBase->doPostSave(Object(Drupal\\group\\Entity\\GroupContent), false)
#7 /home/onion/www/efn/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(774): Drupal\\Core\\Entity\\EntityStorageBase->save(Object(Drupal\\group\\Entity\\GroupContent))
#8 /home/onion/www/efn/modules/contrib/group/src/Entity/Group.php(155): Drupal\\Core\\Entity\\Sql\\SqlContentEntityStorage->save(Object(Drupal\\group\\Entity\\GroupContent))
#9 /home/onion/www/efn/modules/contrib/group/src/Entity/Group.php(190): Drupal\\group\\Entity\\Group->addContent(Object(Drupal\\user\\Entity\\User), 'group_membershi...', Array)
#10 /home/onion/www/efn/modules/contrib/group/src/Entity/Group.php(341): Drupal\\group\\Entity\\Group->addMember(Object(Drupal\\user\\Entity\\User), Array)
#11 /home/onion/www/efn/core/lib/Drupal/Core/Entity/EntityStorageBase.php(506): Drupal\\group\\Entity\\Group->postSave(Object(Drupal\\Core\\Entity\\Sql\\SqlContentEntityStorage), false)
#12 /home/onion/www/efn/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php(641): Drupal\\Core\\Entity\\EntityStorageBase->doPostSave(Object(Drupal\\group\\Entity\\Group), false)
#13 /home/onion/www/efn/core/lib/Drupal/Core/Entity/EntityStorageBase.php(432): Drupal\\Core\\Entity\\ContentEntityStorageBase->doPostSave(Object(Drupal\\group\\Entity\\Group), false)
#14 /home/onion/www/efn/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(774): Drupal\\Core\\Entity\\EntityStorageBase->save(Object(Drupal\\group\\Entity\\Group))
#15 /home/onion/www/efn/core/lib/Drupal/Core/Entity/Entity.php(390): Drupal\\Core\\Entity\\Sql\\SqlContentEntityStorage->save(Object(Drupal\\group\\Entity\\Group))
#16 /home/onion/www/efn/core/lib/Drupal/Core/Entity/EntityForm.php(296): Drupal\\Core\\Entity\\Entity->save()
#17 /home/onion/www/efn/modules/contrib/group/src/Entity/Form/GroupForm.php(99): Drupal\\Core\\Entity\\EntityForm->save(Array, Object(Drupal\\Core\\Form\\FormState))
#18 [internal function]: Drupal\\group\\Entity\\Form\\GroupForm->save(Array, Object(Drupal\\Core\\Form\\FormState))
#19 /home/onion/www/efn/core/lib/Drupal/Core/Form/FormSubmitter.php(111): call_user_func_array(Array, Array)
#20 /home/onion/www/efn/core/lib/Drupal/Core/Form/FormSubmitter.php(51): Drupal\\Core\\Form\\FormSubmitter->executeSubmitHandlers(Array, Object(Drupal\\Core\\Form\\FormState))
#21 /home/onion/www/efn/core/lib/Drupal/Core/Form/FormBuilder.php(589): Drupal\\Core\\Form\\FormSubmitter->doSubmitForm(Array, Object(Drupal\\Core\\Form\\FormState))
#22 /home/onion/www/efn/core/lib/Drupal/Core/Form/FormBuilder.php(318): Drupal\\Core\\Form\\FormBuilder->processForm('group_project_a...', Array, Object(Drupal\\Core\\Form\\FormState))
#23 /home/onion/www/efn/core/lib/Drupal/Core/Entity/EntityFormBuilder.php(48): Drupal\\Core\\Form\\FormBuilder->buildForm('group_project_a...', Object(Drupal\\Core\\Form\\FormState))
#24 /home/onion/www/efn/modules/contrib/group/src/Entity/Controller/GroupController.php(124): Drupal\\Core\\Entity\\EntityFormBuilder->getForm(Object(Drupal\\group\\Entity\\Group), 'add', Array)
#25 [internal function]: Drupal\\group\\Entity\\Controller\\GroupController->addForm(Object(Drupal\\group\\Entity\\GroupType))
#26 /home/onion/www/efn/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#27 /home/onion/www/efn/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()
#28 /home/onion/www/efn/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\\Core\\Render\\Renderer->executeInRenderContext(Object(Drupal\\Core\\Render\\RenderContext), Object(Closure))
#29 /home/onion/www/efn/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#30 /home/onion/www/efn/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()
#31 /home/onion/www/efn/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#32 /home/onion/www/efn/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#33 /home/onion/www/efn/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\\Core\\StackMiddleware\\Session->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#34 /home/onion/www/efn/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\\Core\\StackMiddleware\\KernelPreHandle->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#35 /home/onion/www/efn/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\\page_cache\\StackMiddleware\\PageCache->pass(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#36 /home/onion/www/efn/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\\page_cache\\StackMiddleware\\PageCache->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#37 /home/onion/www/efn/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\\Core\\StackMiddleware\\ReverseProxyMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#38 /home/onion/www/efn/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\\Core\\StackMiddleware\
egotiationMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#39 /home/onion/www/efn/core/lib/Drupal/Core/DrupalKernel.php(665): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#40 /home/onion/www/efn/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#41 {main}, referer: http://efn.localhost/group/add/project
[Fri Feb 15 15:09:19.438594 2019] [php7:notice] [pid 29814] [client ::1:49654] Uncaught PHP Exception Drupal\\Core\\Entity\\EntityStorageException: "SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0248a295-b1b8-43e4-a534-12f40392f182' for key 'group_field__uuid__value': INSERT INTO {groups} (type, uuid, langcode) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2); Array
(
    [:db_insert_placeholder_0] => project
    [:db_insert_placeholder_1] => 0248a295-b1b8-43e4-a534-12f40392f182
    [:db_insert_placeholder_2] => en
)
" at /home/onion/www/efn/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php line 783, referer: http://efn.localhost/group/add/project

**Comment by multilectical** [comment]
3430abd looks like it fixed this one. added check before getting group owner
